// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyLl3VterpJAPoxYH8PKYX00yPCt526pA',
    appId: '1:111648510014:web:1e405aa2df1728c7cc816f',
    messagingSenderId: '111648510014',
    projectId: 'racetrackingapp-g5',
    authDomain: 'racetrackingapp-g5.firebaseapp.com',
    databaseURL: 'https://racetrackingapp-g5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'racetrackingapp-g5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIf6bJq4ZX8c36uWsh235v1zlASLAezeo',
    appId: '1:111648510014:android:6f36ae2d1ed1afa4cc816f',
    messagingSenderId: '111648510014',
    projectId: 'racetrackingapp-g5',
    databaseURL: 'https://racetrackingapp-g5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'racetrackingapp-g5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnZAfjlOc_nLblzg8C9MVGjHE7--B_cVI',
    appId: '1:111648510014:ios:9e23d766ce680e51cc816f',
    messagingSenderId: '111648510014',
    projectId: 'racetrackingapp-g5',
    databaseURL: 'https://racetrackingapp-g5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'racetrackingapp-g5.firebasestorage.app',
    iosBundleId: 'com.example.raceTrackingAppG5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnZAfjlOc_nLblzg8C9MVGjHE7--B_cVI',
    appId: '1:111648510014:ios:9e23d766ce680e51cc816f',
    messagingSenderId: '111648510014',
    projectId: 'racetrackingapp-g5',
    databaseURL: 'https://racetrackingapp-g5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'racetrackingapp-g5.firebasestorage.app',
    iosBundleId: 'com.example.raceTrackingAppG5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyLl3VterpJAPoxYH8PKYX00yPCt526pA',
    appId: '1:111648510014:web:748739a303128524cc816f',
    messagingSenderId: '111648510014',
    projectId: 'racetrackingapp-g5',
    authDomain: 'racetrackingapp-g5.firebaseapp.com',
    databaseURL: 'https://racetrackingapp-g5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'racetrackingapp-g5.firebasestorage.app',
  );
}
